Update Konflux CEL expressions
securesign/secure-sign-operator pull request #250
Opened 2024-03-06 09:57 UTC by JasonPowr

This pr makes changes to the tekton cel expressions, this makes sure that the fbc images, the bundle and the operator can build independently. 

## Explanation (Copied from slack)
"I think having the operator and the bundle in the same application in Konflux causes some issues.When we generate an image for the operator-controller in Konflux, we then go back and update the bundle. When we update the bundle it generates a new image for the operator-controller, this means that when we release we use a snapshot that has an up to date controller image, but the image being used in the bundle isn’t the one in the snapshot, it's the one generated previously. If we were to separate them into different applications they could be built independently, wdyt? Or probably a better solution would be to add the cel expression to the operator pipelines?"

2024-03-06 14:30 UTC, lance requested changes
Can you add `go.sum` and `Makefile` to the operator pipelines?

2024-03-06 14:30 UTC, lance commented on .tekton/rhtas-operator-pull-request.yaml
> +      event == "pull_request" && target_branch == "main" && (".tekton/rhtas-operator-pull-request.yaml".pathChanged() || "api/***".pathChanged() || "config/***".pathChanged() || "controllers/***".pat
I don't love this, since it won't catch new files or directories at the root. But I'm not sure what is a better way to handle it. You might add `go.sum` and `Makefile` to this list.

2024-03-06 14:30 UTC, lance commented on .tekton/rhtas-operator-push.yaml
> +      event == "push" && target_branch == "main" && (".tekton/rhtas-operator-push.yaml".pathChanged() || "api/***".pathChanged() || "config/***".pathChanged() || "controllers/***".pathChanged() || "D
As above with `go.sum` and `Makefile`.

2024-03-06 14:50 UTC, JasonPowr commented on .tekton/rhtas-operator-pull-request.yaml
> +      event == "pull_request" && target_branch == "main" && (".tekton/rhtas-operator-pull-request.yaml".pathChanged() || "api/***".pathChanged() || "config/***".pathChanged() || "controllers/***".pat
I get what your saying, but at the same time if a new directory or file is introduced that affects the build of the operator, there would  be changes in the directories listed in the expression to reflect whatever changes are needed. 

I've added `go.sum` and `Makefile` :)

2024-03-08 17:12 UTC, lance commented
/lgtm

2024-03-08 18:06 UTC, merged