[DOCS] Jenkins docs for signing and verifying using a Jenkins pipeline
securesign/secure-sign-operator pull request #303
Opened 2024-04-03 10:47 UTC by JasonPowr

Small doc related pr

2024-04-04 11:11 UTC, lance approved these changes
Thanks!

2024-04-27 16:13 UTC, sabre1041 requested changes

2024-04-27 16:13 UTC, sabre1041 commented on docs/sign_and_verify_jenkins.md
> +                            ${env.OIDC_ISSUER_URL}/protocol/openid-connect/token | sed -E 's/.*"access_token":"([^"]*)".*/\\1/' > token.txt
```suggestion
                            ${env.OIDC_ISSUER_URL}/protocol/openid-connect/token | sed -E 's/.*"id_token":"([^"]*)".*/\\1/' > token.txt
```

2024-04-27 16:13 UTC, sabre1041 commented on docs/sign_and_verify_jenkins.md
> +                    cosign verify --rekor-url=${env.REKOR_URL} --certificate-identity-regexp ${env.OIDC_USERNAME} --certificate-oidc-issuer-regexp ${env.OIDC_ISSUER} ${env.IMG}:${env.TAG}
Lets use the `--certificate-identity` flag since we know the concrete identity

2024-04-27 16:13 UTC, sabre1041 commented on docs/sign_and_verify_jenkins.md
> +                    image 'registry.redhat.io/rhtas-tech-preview/cosign-rhel9:0.0.2'
```suggestion
                    image 'registry.redhat.io/rhtas/cosign-rhel9:1.0.0'
```

2024-04-27 16:13 UTC, sabre1041 commented on docs/sign_and_verify_jenkins.md
> +Credentials will need to be set using the credentials plugin, there are three in total that will need to be configured.
```suggestion
Credentials will need to be set using the credentials plugin. There are three credentials in total that will need to be configured.
```

2024-04-27 16:13 UTC, sabre1041 commented on docs/sign_and_verify_jenkins.md
> +    * During the cosign signing process, cosign pushes the signed image to an image registry, because of this it needs credentials, which should be setup in a similar fashion to the above, in the exa
```suggestion
    * During the cosign signing process, cosign pushes the signed image to an image registry. As a result, credentials are needed which should be setup in a similar fashion to the above. In this example, quay.io is the registry used and credentials (ID is defaulted to `quay_credentials`) are configured like so:
```

2024-04-27 16:13 UTC, sabre1041 commented on docs/sign_and_verify_jenkins.md
> +    * A password, for the OIDC provider will also need to be configured using the credentials plugin (ID is defaulted to `oidc-password`) this should be setup in a similar fashion to the above, but i
```suggestion
    * A password for the OIDC provider will also need to be configured using the credentials plugin (ID is defaulted to `oidc-password`). This should be setup in a similar fashion to the above, but it should be created as a `Secret text` as opposed to a `Username with Password`
```

2024-04-27 16:13 UTC, sabre1041 commented on docs/sign_and_verify_jenkins.md
> +To Create a pipeline, Dashboard > New item > Pipeline, Pipelines can be created using scm (Source Control Managment) but in this example we use a simple pipeline script, that signs and verify's an im
```suggestion
To Create a pipeline, select Dashboard > New item > Pipeline. Pipelines can be created using scm (Source Control Management), but in this example, we use a simple pipeline script that signs and verify's an image. An example can be found below.
```

2024-04-29 10:26 UTC, JasonPowr commented
I've had to update how the pipeline uses cosign credentials, as When deploying this it wasn't working (this time), I believe previously the config for docker within the pipeline was already authenticated with quay, meaning it was skipping the setp each time

2024-07-22 18:26 UTC, lance commented
@JasonPowr what is the status of this PR?

2024-07-23 07:26 UTC, JasonPowr commented
> @JasonPowr what is the status of this PR?

@lance This pr should be good to go, although there may be better documentation out there by now

2024-11-04 08:35 UTC, closed without merging