fix: Set the common name of the Fulcio cert automatically
securesign/secure-sign-operator pull request #365
Opened 2024-05-10 10:43 UTC by JasonPowr

Jira: https://issues.redhat.com/browse/SECURESIGN-851

This pr moves the creation of the service an ingress before the creation of the Fulcio cert, allowing us to get the URL and automatically set the Fulcio common name.

2024-05-10 11:04 UTC, bouskaJ commented on controllers/fulcio/utils/fulcio_secrets.go
> +	ctx := context.Background()
I believe, we should pass `context` from the root function rather than create new one. With new context the application can't cancel operation on graceful shutdown.

2024-05-10 14:17 UTC, osmman requested changes

2024-05-10 14:17 UTC, osmman commented on api/v1alpha1/fulcio_types.go
> -	CommonName string `json:"commonName,omitempty"`
Do not remove this option. It will broke compatibility with old 1.0.x channel and it will remove feature to customize common name. 

We cannot fully depends on host from Ingress because the users can have their own specific configuration and they need to customize it.

2024-05-10 14:31 UTC, osmman commented on controllers/fulcio/utils/fulcio_secrets.go
> +		err := client.Get(ctx, types.NamespacedName{Name: deploymentName, Namespace: instance.Namespace}, ingress)
Ingress object do not exists in phase which this action is executed.
handle cert action is executed during  `Pending` phase, Ingress action is executed during `Creating` phase

2024-05-10 15:15 UTC, JasonPowr commented on api/v1alpha1/fulcio_types.go
> -	CommonName string `json:"commonName,omitempty"`
```
Do not remove this option. It will broke compatibility with old 1.0.x channel and it will remove feature to customize common name.
```

Thanks for this, something I always forget about need to make a note for myself of it for future work

2024-05-10 15:17 UTC, JasonPowr commented on controllers/fulcio/utils/fulcio_secrets.go
> +		err := client.Get(ctx, types.NamespacedName{Name: deploymentName, Namespace: instance.Namespace}, ingress)
I have moved the ingress & service creation to the pending phase to facilitate this: https://github.com/securesign/secure-sign-operator/pull/365/files#diff-444aef5e7f264fafa6b15d801f33ad3982d46a27f77badc3ff210a84c137aeeaR89-R90

2024-05-10 15:47 UTC, osmman commented on controllers/fulcio/utils/fulcio_secrets.go
> +		err := client.Get(ctx, types.NamespacedName{Name: deploymentName, Namespace: instance.Namespace}, ingress)
It is not good to move it from creating phase. Rather then dig information from ingress object you can reuse function which calculate host name

2024-05-13 10:45 UTC, osmman commented on controllers/fulcio/utils/fulcio_secrets.go
> +			if instance.Spec.Certificate.CommonName, err = kubernetes.CalculateHostname(ctx, client, deploymentName, instance.Namespace); err != nil {
`instance.Spec.ExternalAccess.Host` should be used if it is set

2024-05-13 10:48 UTC, osmman commented on api/v1alpha1/fulcio_types.go
> -// +kubebuilder:validation:XValidation:rule=(has(self.caRef) || self.commonName != ""),message=commonName cannot be empty
We should extend doc to inform that `commonName` will be calculated based on host name if it is not set

2024-05-13 10:50 UTC, osmman commented
PR targeted for 1.1.0 release
/hold

2024-05-13 13:47 UTC, JasonPowr commented on controllers/fulcio/utils/fulcio_secrets.go
> +			if instance.Spec.Certificate.CommonName, err = kubernetes.CalculateHostname(ctx, client, deploymentName, instance.Namespace); err != nil {
If we do this, we are going to have to make `instance.Spec.ExternalAccess.Host` required by default to make sure a value gets set, is this ok?

At this stage `instance.Spec.ExternalAccess.Host` is equal to whatever is defined in the crd definition as it doesn't get set until later in the loop.

2024-05-13 14:24 UTC, osmman commented on controllers/fulcio/utils/fulcio_secrets.go
> +			if instance.Spec.Certificate.CommonName, err = kubernetes.CalculateHostname(ctx, client, deploymentName, instance.Namespace); err != nil {
```
if CommonName empty {
   if ExternalAccess.Enable {
     if ExternalAccess.Host != "" {
        return ExternalAccess.Host
     } else {
        return CalculateHostname()
     }
   } else {
     return "fulcio.svc.local"
   }
}
```

2024-05-14 10:27 UTC, osmman approved these changes

2024-05-23 09:57 UTC, JasonPowr commented
Fix for upgrade test: https://github.com/securesign/secure-sign-operator/pull/389

2024-05-23 10:36 UTC, bouskaJ commented
/LGTM

2024-05-23 10:41 UTC, JasonPowr commented
/unhold

2024-05-23 10:41 UTC, merged

2024-05-30 12:19 UTC, osmman commented
/cherrypick release-1.0