[SECURESIGN-844] Migrate to kubebuilder go/v4
securesign/secure-sign-operator pull request #431
Opened 2024-06-06 12:46 UTC by bouskaJ

2024-06-07 07:31 UTC, bouskaJ commented
in order to pass `tas-operator-e2e` https://github.com/openshift/release/pull/52925 needs to be merged

2024-06-11 09:34 UTC, osmman requested changes

2024-06-11 09:34 UTC, osmman commented on Makefile
>  	docker build . -t ${IMG}
it should use `$(CONTAINER_TOOL)`

2024-06-11 09:34 UTC, osmman commented on Makefile
> +CONTROLLER_TOOLS_VERSION ?= v0.13.0
We should use original version and do not downgrade.

2024-06-11 09:34 UTC, osmman commented on Makefile
https://github.com/securesign/secure-sign-operator/pull/431/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L269 should be changed to use `$(CONTAINER_TOOL)`

2024-06-11 09:34 UTC, osmman commented on bundle/manifests/rhtas.redhat.com_ctlogs.yaml
please regenerate all manifests files with newer version 0.14.0 of controller-gen

2024-06-11 09:34 UTC, osmman commented on bundle.Dockerfile
> +LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.34.0
There are used multiple version of operator sdk in the project. It should be fixed to use single one.
I saw 1.34.0, 1.34.1, 1.34.2

2024-06-11 09:34 UTC, osmman commented on cmd/main.go
> -	flag.StringVar(&pprofAddr, "pprof-address", "", "The address to expose the pprof server. Default is empty string which disables the pprof server.")
We need this one, it has been added by me.

2024-06-11 09:34 UTC, osmman commented on cmd/main.go
> -		PprofBindAddress:       pprofAddr,
return it back

2024-06-11 10:58 UTC, osmman commented
`.tekton` pipelines need to be updated to use new paths. Controller and main.go has been moved so it should test internal, api and cmd folders

https://github.com/securesign/secure-sign-operator/blob/06fade2d547bc5f5d5c8d0a67d4bf19f512ccc23/.tekton/rhtas-operator-push.yaml#L10
https://github.com/securesign/secure-sign-operator/blob/06fade2d547bc5f5d5c8d0a67d4bf19f512ccc23/.tekton/rhtas-operator-pull-request.yaml#L11

2024-06-11 11:19 UTC, osmman commented on Makefile
> +CONTROLLER_TOOLS_VERSION ?= v0.13.0
`make generate` command is failing on null pointer exception with 0.13.0. It will pass when I upgrade it to 0.14.0

2024-06-12 12:44 UTC, osmman requested changes
Please regenerate config and bundle resources by controller-gen v0.14.0

2024-06-12 14:56 UTC, osmman commented
/lgtm

2024-06-12 14:58 UTC, osmman commented
/override tas-operator-e2e

2024-06-12 14:58 UTC, osmman commented
/override ci/prow/tas-operator-e2e

2024-06-13 07:28 UTC, bouskaJ commented
/override ci/prow/tas-operator-e2e

2024-06-13 07:29 UTC, merged

2024-06-13 07:30 UTC, bouskaJ commented
@bouskaJ File paths changed. Can you check all other components for `build.appstudio.openshift.io/build-nudge-files: "internal/controller/constants/*"`?