[SECURESIGN-1044] Error handler
securesign/secure-sign-operator pull request #443
Opened 2024-06-14 12:21 UTC by bouskaJ

This is my proposal on how to solve https://issues.redhat.com/browse/SECURESIGN-1001 or similar issues.

2024-06-14 12:22 UTC, bouskaJ commented
/hold

we need to implement similar functionality for CTlog before decreasing `CreateTreeDeadline` timeout.

2024-06-14 12:22 UTC, bouskaJ commented
@JasonPowr @tommyd450 @osmman WDYT?

2024-06-17 09:28 UTC, osmman requested changes

2024-06-17 09:28 UTC, osmman commented on internal/controller/common/action/base_action.go
> +	return &Result{Result: reconcile.Result{RequeueAfter: 30 * time.Second}}
Keep original functionality and rather create a new method `RequeueWithStatusUpdate`

2024-06-17 09:31 UTC, osmman commented on internal/controller/rekor/actions/error.go
> +func (i handleErrorAction) CanHandle(_ context.Context, instance *rhtasv1alpha1.Rekor) bool {
We will need to add some type of brake which will limit number of retries to not ends with infinite loop.

2024-06-20 07:59 UTC, bouskaJ commented on internal/controller/common/action/base_action.go
> +	return &Result{Result: reconcile.Result{RequeueAfter: 30 * time.Second}}
Calling the original function is not safe. After setting the `Failure` status, the only correct way to invoke the ErrorHandler is `RequeueAfter`. Calling the original function will result in new intermediate loop invocation. The ErrorHandler will try to restart and we will end-up in infinite loop **without any timeout**.

2024-06-20 08:00 UTC, bouskaJ commented on internal/controller/rekor/actions/error.go
> +func (i handleErrorAction) CanHandle(_ context.Context, instance *rhtasv1alpha1.Rekor) bool {
I kept the way that is implemented on Pod lifecycle (`Always`,`OnFailure` actions restarts the pod infinite number of times). I do agree, we need to implement some sort of strategy to stop it. This is only PoC.

2024-07-02 09:06 UTC, bouskaJ commented
/unhold

2024-07-12 10:21 UTC, osmman requested changes
**Missing logic to reset Restart counter:**
Currently, there is no mechanism to reset the retry counter after a successful recovery from failure. As a result, the number of attempts is limited to a fixed value for the entire lifecycle of the object.

**Unclear need for Restarting phase:**
The introduction of a new Restarting phase is confusing, and its purpose is not well-defined. Documentation is needed to explain the meaning of all phases and how they relate to each other.

**Error handling order:**
Errors are not being handled by the designated error handlers. Instead, the first action in the sequence always consumes the error, which can lead to repeated deletion and recreation of objects without reaching the appropriate error handler.

**Lack of Fail-Fast mechanism:**
There is no way to configure the operator to interrupt reconciliation without attempting to recover from failures (fail-fast). Most failures should simply cause the reconciliation to stop, rather than trying to recover. Recover functionality should be reserved for only a small subset of actions that can genuinely recover from their failed state.

2024-07-12 10:21 UTC, osmman commented on internal/controller/rekor/actions/server/generate_signer.go
> +func (g generateSigner) HandleError(ctx context.Context, instance *rhtasv1alpha1.Rekor) *action.Result {
I would recommend against attempting error recovery for similar events. It is better to adhere to a fail-fast approach in this context. In other words, if something goes wrong, stop the reconciliation process immediately.

2024-07-12 10:21 UTC, osmman commented on api/v1alpha1/ctlog_types.go
> +	Restarts int `json:"restarts,omitempty"`
I am not sure that `Restarts` is a good name. It is to vague and generic. Something like:
- RetryCount
- RecoveryRetryCount
- FailureRecoveryAttempts
- RecoveryAttempts
- RetryAttempts

2024-07-15 10:03 UTC, osmman commented on internal/controller/constants/constants.go
> +	Restarting = "Restarting"
```go
// The operator has encountered a recoverable error and is attempting to recover. This state includes a counter (RecoveryAttempts) to track the number of recovery attempts.
Recovering  = "Recovering"
// The operator has encountered an unrecoverable error or exceeded the maximum number of recovery attempts. Reconciliation stops.
Failure          = "Failure"
// An error has occurred, but it’s not yet classified as recoverable or irrecoverable. This state can transition to either Recovering or Failed based on error type and policy.
Error             = "Error"
```

2024-07-16 12:10 UTC, bouskaJ commented on internal/controller/rekor/actions/server/generate_signer.go
> +func (g generateSigner) HandleError(ctx context.Context, instance *rhtasv1alpha1.Rekor) *action.Result {
I created special return type `i.FailedWithStatusUpdate`. I agree that we can throw it for example on wrong user input but it does make sense retry operator-generated keys.

2024-07-23 13:03 UTC, osmman commented on api/v1alpha1/rekor_types.go
> +	// Number of component restart attempts.
```suggestion
	// Number of component recovery attempts.
```

2024-07-23 13:07 UTC, osmman commented on cmd/main.go
> +	flag.Int64Var(&constants.AllowedRestarts, "allowed-restarts", constants.AllowedRestarts, "Allowed restart threshold.")
```suggestion
	flag.Int64Var(&constants.AllowedRecoveryAttempts, "allowed-recovery-attempts", constants.AllowedRecoveryAttempts, "Specifies the maximum number of recovery attempts allowed before an operation is considered failed.")
```

2024-07-23 13:27 UTC, osmman commented on internal/controller/common/action/transitions/restart_on_error.go
> +		return i.FailWithStatusUpdate(ctx, fmt.Errorf("restart threshold reached"), instance)
```suggestion
		return i.FailWithStatusUpdate(ctx, fmt.Errorf("recovery threshold reached"), instance)
```

2024-07-23 13:32 UTC, osmman commented on internal/controller/common/action/transitions/restart_on_error.go
> +func NewRestartOnErrorAction[T apis.ConditionsAwareObject]() action.Action[T] {
Could you please add tests for the **RestartOnError** action? It's crucial to have this action thoroughly covered by tests since it will be heavily utilized. Ensuring test coverage will help prevent potential breakages in future changes.

2024-07-23 14:29 UTC, osmman commented on internal/controller/common/utils/kubernetes/deployment.go
>  func DeploymentIsRunning(ctx context.Context, cli client.Client, namespace string, labels map[string]string) (bool, error) {
I think that we should depend Deployment's `Available` condition. It will work much better in feature where we will need to depend on minimum available replicas for HA.

```yaml
kind: Deployment
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 0 # 🔰
status:
  conditions:
    - lastTransitionTime: "2020-07-07T14:04:27Z"
      lastUpdateTime: "2020-07-07T14:04:27Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2020-07-07T14:04:27Z"
      lastUpdateTime: "2020-07-07T14:04:27Z"
      message: 'pods "test-7df57bd99d-5qw47" is forbidden: exceeded quota: mem-cpu-demo, requested: requests.memory=50Mi, used: requests.memory=200Mi, limited: requests.memory=200Mi'
      reason: FailedCreate
      status: "True"
      type: ReplicaFailure
    - lastTransitionTime: "2020-07-07T14:04:27Z"
      lastUpdateTime: "2020-07-07T14:04:38Z"
      message: ReplicaSet "test-7df57bd99d" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
  replicas: 4
  availableReplicas: 4
  readyReplicas: 4
  unavailableReplicas: 1
  updatedReplicas: 4
```

2024-07-23 15:30 UTC, osmman commented on internal/controller/common/action/base_action.go
> +	action.Recorder.Event(instance, v1.EventTypeWarning, constants.Error, err.Error())
lets add information which action produced error. We have two options modify message body to contains `action.name()`: 
```
action.Recorder.Eventf(instance, v1.EventTypeWarning, constants.Error, "%s: %s", action.name(), err.Error())
```

or produce annotated event:
```
action.Recorder.AnnotatedEventf(instance, map[string]string{"action":action.name()},v1.EventTypeWarning, constants.Error, "%s: %s", action.name(), err.Error())
```

2024-07-23 15:33 UTC, osmman commented on internal/controller/common/action/base_action.go
> +
lets automaticaly add condition for failed action, that could be used for CanHandleError to to identify it's responsibility for recovery.

```
instance.SetCondition(metav1.Condition{Type: action.name(), Reason: constant.Error})
```

2024-07-25 08:48 UTC, bouskaJ commented on internal/controller/common/action/base_action.go
> +	action.Recorder.Event(instance, v1.EventTypeWarning, constants.Error, err.Error())
`action.Name()` is not available on `BaseAction` it would need more code alignment. I would not like to mixed with this already complex PR.

2024-07-25 11:44 UTC, osmman commented on internal/controller/common/action/base_action.go
> +	return &Result{Result: reconcile.Result{RequeueAfter: 1 * time.Minute}}
Currently our tests take 10x more time to be executed and I think that it has been caused by this 1 minute requeue. We should use smaller value for default behavior and if some action relay need some time than we should define it in that action. 5-10 second could work

2024-07-25 12:57 UTC, bouskaJ commented on internal/controller/common/action/base_action.go
> +	return &Result{Result: reconcile.Result{RequeueAfter: 1 * time.Minute}}
I modified some timeouts. We should be fine now.

2024-07-25 14:00 UTC, osmman commented on internal/controller/common/action/base_action.go
> +	// wait for 1 minute and invoke error-handler
```suggestion
	// wait for 10 second and invoke error-handler
```

2024-07-25 15:05 UTC, osmman commented on internal/controller/rekor/actions/server/generate_signer.go
> +	if err = controllerutil.SetControllerReference(instance, secret, g.Client.Scheme()); err != nil {
do not modify behavior of this action, secret should not be deleted

2024-07-25 15:07 UTC, osmman commented on internal/controller/rekor/actions/server/monitoring.go
> +	return !meta.IsStatusConditionTrue(instance.GetConditions(), actions.ServerCondition) && instance.Spec.Monitoring.Enabled && (err == nil || !errors.IsNotFound(err))
```suggestion
	return meta.IsStatusConditionFalse(instance.GetConditions(), actions.ServerCondition) && instance.Spec.Monitoring.Enabled && (err == nil || !errors.IsNotFound(err))
```

2024-07-25 15:12 UTC, osmman commented on internal/controller/rekor/actions/ui/svc.go
> +	return *instance.Spec.RekorSearchUI.Enabled && !meta.IsStatusConditionTrue(instance.GetConditions(), actions.UICondition) && (err == nil || !errors.IsNotFound(err))
nil in `instance.Spec.RekorSearchUI.Enabled` will cause panic error

2024-07-25 15:13 UTC, osmman commented on internal/controller/rekor/rekor_controller.go
>  			if *rekor.Spec.RekorSearchUI.Enabled {
https://github.com/securesign/secure-sign-operator/pull/443/files#r1691636450

2024-07-25 15:13 UTC, osmman commented on internal/controller/rekor/rekor_controller.go
> +			if *rekor.Spec.BackFillRedis.Enabled {
https://github.com/securesign/secure-sign-operator/pull/443/files#r1691636450

2024-07-26 04:50 UTC, bouskaJ commented on internal/controller/rekor/actions/server/monitoring.go
> +	return !meta.IsStatusConditionTrue(instance.GetConditions(), actions.ServerCondition) && instance.Spec.Monitoring.Enabled && (err == nil || !errors.IsNotFound(err))
I use ` !meta.IsStatusConditionTrue` on purpose. It will run on `ConditionUnknown` too.

2024-07-29 15:25 UTC, osmman commented on internal/controller/common/action/base_action.go
> +func (action *BaseAction) Error(err error) *Result {
Error function do not work correctly at least it do not behave live ErrorWithStatusUpdate. 
Event our return values are incorrect controller returns this warning:
```
Warning: Reconciler returned both a non-zero result and a non-nil error. The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff. For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler
```

2024-07-30 07:19 UTC, osmman commented
/hold

2025-01-14 11:46 UTC, bouskaJ commented
This PR is out of date - there is too many conflicting files and the error handler approach is partially handled by https://github.com/securesign/secure-sign-operator/blob/main/internal/controller/common/action/base_action.go#L77 (Terminal/non-Terminal errors)

2025-01-14 11:46 UTC, closed without merging