SECURESIGN-1014 | Add support for Trusted Timestamp Authorities in SecureSign
securesign/secure-sign-operator pull request #456
Opened 2024-06-21 08:05 UTC by JasonPowr

Opening this as a draft pr, so far this is just the basic deployment of the Timestamp Authority. just looking for some feedback.

## Testing
1. Build and deploy operator
2.  TSA should come up with the rest of the stack
3. Sign an image with the flag `--timestamp-server-url=$TSA_URL` eg
```
TSA_URL=https://<tsa-url>/api/v1/timestamp
cosign sign -y --timestamp-server-url=$TSA_URL <image>
```
4. To verify the timestamp you need to retrieve the `certificate chain` using `curl https://<tsa-url>/api/v1/timestamp/certchain > ts_chain.pem`, then run the `cosign verify` cmd like so:
```
cosign verify --timestamp-certificate-chain=ts_chain_local.pem <image>
```

## Todo
1. Extend the API to support more options
6. Add testing

## Notes
-  Currently using memory as the signer type, this will be changes as its not recommended for production

2024-06-24 14:50 UTC, osmman commented on internal/controller/tsa/utils/tsa_deployment.go
> +								"--timestamp-signer=memory",
and we need these certs and public keys to be distributed into TUF service

2024-07-18 08:08 UTC, JasonPowr commented
/test tas-operator-e2e

2024-07-18 09:36 UTC, osmman commented on api/v1alpha1/common.go
> +type KmsAuthConfig struct {
I think that this type could be reduced to simply reuse core.EnvVar. Like this:

```
// KmsAuthConfig specifies environment variable for KMS authentication.
type KmsAuthConfig core.EnvVar

type KmsSigner struct {
   KmsAuthEnv []KmsAuthConfig `json:"auth,omitempty"`
}
```

2024-07-18 09:40 UTC, osmman commented on api/v1alpha1/timestampauthority_types.go
> +type TimestampAuthoritySigner struct {
Is configuration with multiple signers valid? For example:
```
spec:
  signer:
    file:
      keyRef: ...
    tika:
      keyResource: ...
```

It it is not than we should add validation rule to bloc it.

2024-07-18 10:09 UTC, osmman commented on internal/controller/tsa/actions/deployment.go
> +func (i deployAction) Handle(ctx context.Context, instance *rhtasv1alpha1.TimestampAuthority) *action.Result {
We need to add support to inject proxy and trusted CA for TSA deployment. This can be done by there medhods:
- https://github.com/securesign/secure-sign-operator/blob/main/internal/controller/common/utils/set_proxy.go
- https://github.com/securesign/secure-sign-operator/blob/main/internal/controller/common/utils/set_trusted_ca.go

2024-07-18 13:05 UTC, JasonPowr commented on api/v1alpha1/timestampauthority_types.go
> +	TinkHcvaultTokenRef *SecretKeySelector `json:"tinkHcvaultTokenRef,omitempty"`
It could be achieved with KmsAuthConfig your right, but TSA provides a flag for it so I said I would include it

2024-07-18 13:06 UTC, JasonPowr commented on api/v1alpha1/timestampauthority_types.go
> +type TimestampAuthoritySigner struct {
Its not valid, good point I will add the validation

2024-07-22 07:30 UTC, osmman commented on internal/controller/tsa/utils/tsa_deployment.go
> +	return &apps.Deployment{
please add readiness and health checks probes for TSA deployment. https://github.com/securesign/timestamp-authority/blob/main/docker-compose.yml#L35

2024-07-22 07:43 UTC, osmman commented on api/v1alpha1/timestampauthority_types.go
> +type TimestampAuthoritySpec struct {
I think that we should add option to enable of configuration ntp monitor. You can find config files schema [here](https://github.com/securesign/timestamp-authority/blob/main/pkg/ntpmonitor/config.go). [This](https://github.com/securesign/timestamp-authority/blob/main/pkg/ntpmonitor/ntpsync.yaml) is default configuration of it.

2024-07-29 10:15 UTC, JasonPowr commented
/test tas-operator-e2e

2024-07-29 11:51 UTC, bouskaJ commented on internal/controller/tsa/actions/generate_signer.go
> +				key, err := ecdsa.GenerateKey(elliptic.P384(), rand.Reader)
Is there anything common we can share with `Rekor` we can share? Both components generate signer with all related keys.... See https://github.com/securesign/secure-sign-operator/blob/main/internal/controller/rekor/actions/server/generate_signer.go#L200

2024-07-29 12:48 UTC, osmman requested changes
The current implementation of the TSA API looks good overall.

However, I would like to request some additional changes to ensure thorough testing and integration. Firstly, please add multiple unit tests for the TSA component, focusing specifically on the **generateSigner** and **ntpMonitoringAction** actions. Our experience shows that most bugs in our operator stem from user modify values in **spec**, and having robust unit tests for these actions will help mitigate this issue.

Additionally, extend the current controller tests to verify that objects and resources are correctly generated. Alongside this, please create a new test case to cover the hot update scenario, ensuring that the controller handles this situation appropriately.

Lastly, modify our end-to-end (e2e) tests to integrate the new TSA component, with a particular focus on upgrade testing.

2024-07-29 12:48 UTC, osmman commented on internal/controller/tsa/actions/ntpMonitoring.go
> +		configMap := kubernetes.CreateConfigMap(NtpCMName, instance.Namespace, labels, map[string]string{"ntp-config.yaml": string(ntpConfig)})
it is better to use immutable configmaps, the main reason is change of cfg will automatically force deployment to apply new config. You can use  `kubernetes.CreateImmutableConfigmap` function

2024-07-29 13:05 UTC, JasonPowr commented on internal/controller/tsa/actions/generate_signer.go
> +				key, err := ecdsa.GenerateKey(elliptic.P384(), rand.Reader)
Ill take a look thanks for the review :)

2024-07-29 13:05 UTC, JasonPowr commented on internal/controller/tsa/actions/ntpMonitoring.go
> +		configMap := kubernetes.CreateConfigMap(NtpCMName, instance.Namespace, labels, map[string]string{"ntp-config.yaml": string(ntpConfig)})
Thanks Tomas appreciate the review :)

2024-08-16 11:21 UTC, JasonPowr commented
/test tas-operator-e2e

2024-08-16 14:40 UTC, JasonPowr commented
/test tas-operator-e2e

2024-08-19 10:21 UTC, osmman commented on internal/controller/securesign/securesign_controller.go
> +//+kubebuilder:rbac:groups=core,resources=configmaps,verbs=get;list;watch;create;update;patch;delete;deletecollection
If i understand correctly right now you do not need `deletecollection` permittion at least I unable to find any usage of it.

2024-08-19 10:32 UTC, JasonPowr commented on internal/controller/securesign/securesign_controller.go
> +//+kubebuilder:rbac:groups=core,resources=configmaps,verbs=get;list;watch;create;update;patch;delete;deletecollection
I think, please correct me if I am wrong :), but I need it here https://github.com/securesign/secure-sign-operator/blob/513bfc98c4e6897fde7a55757f778497c696595b/internal/controller/tsa/actions/ntpMonitoring.go#L72 to delete unused config maps for ntp monitoring. Unless we want to keep a history of some sort like we now do with the certificate?

2024-08-19 10:46 UTC, osmman commented on internal/controller/securesign/securesign_controller.go
> +//+kubebuilder:rbac:groups=core,resources=configmaps,verbs=get;list;watch;create;update;patch;delete;deletecollection
sorry, you are correct. For some reason I missed `DeleteAllOf` when i search for it's usage.

2024-08-19 11:22 UTC, osmman reviewed
I installed sample Securesign resource and I am getting this status condition on TSA object:
```
status:
  conditions:
    - message: ''
      reason: Ready
      status: 'True'
      type: Ready
    - message: ''
      reason: Pending
      status: Unknown
      type: TSASignerCondition
    - message: Ingress created
      reason: Creating
      status: 'False'
      type: TSAServerCondition
```

It looks like that TSA service has been deployed correctly but status of TSASignerCondition and TSAServerCondition are not positive.

2024-08-19 11:23 UTC, osmman commented on internal/controller/tsa/actions/generate_signer_test.go
> +	g := NewWithT(t)
it is not required, only optional to make development a little bit nicer

2024-08-19 12:40 UTC, JasonPowr commented
@osmman Should be resolved now, I also made those changes to the test 

```
status:
  conditions:
  - lastTransitionTime: "2024-08-19T12:37:36Z"
    message: ""
    reason: Ready
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-08-19T12:37:26Z"
    message: ""
    reason: Resolved
    status: "True"
    type: TSASignerCondition
  - lastTransitionTime: "2024-08-19T12:37:36Z"
    message: ""
    reason: Ready
    status: "True"
    type: TSAServerCondition
```

2024-08-19 13:14 UTC, osmman approved these changes
/lgtm

2024-08-19 13:36 UTC, JasonPowr commented
/unhold

2024-08-19 13:36 UTC, merged