[SECURESIGN-663] Add option to set external ctlog service. Refactor services port name.
securesign/secure-sign-operator pull request #458
Opened 2024-06-21 14:23 UTC by fghanmi

Refactor done on: [Ctlog, Trillian]
Another PR will be created for the rest of components.

2024-06-21 15:36 UTC, fghanmi commented
/retest

2024-06-25 12:52 UTC, fghanmi commented
/retest

2024-06-25 13:12 UTC, osmman requested changes

2024-06-25 13:12 UTC, osmman commented on internal/controller/common/utils/kubernetes/service.go
> +func CreateService(namespace string, name string, portName string, port int, labels map[string]string) *corev1.Service {
Please create a separate PR for refactoring `CreateService` method and it's required changes.

2024-06-25 14:57 UTC, fghanmi commented
To be declined: 
Will create sub PRs instead.

2024-06-25 14:59 UTC, closed without merging