feat: Add rekor search ui
securesign/secure-sign-operator pull request #46
Opened 2024-01-17 16:23 UTC by JasonPowr

This pr aims to add the rekor search ui into the operator. Completes: https://github.com/securesign/secure-sign-operator/issues/39

## Testing
1. Usual, cluster, login, build, deploy
2. Create ns `oc create ns trusted-artifact-signer`
3. In your yaml file make sure  `rekor.rekorSearchUI.external = true` to expose the route
4. Apply the yaml file
5. Go to Networking -> Routes -> Rekor-Search-UI
6. When you visit the page you will need to manually input the rekor server url by clicking the gear in the top right
7. You should be able to view info then (sign and verify so there is something there to see ).

2024-01-18 12:20 UTC, JasonPowr commented
@bouskaJ, @cooktheryan  I've had to make some adjustments to how ingress is handled for rekor as with this pr there is more than one for the rekor component, let me know if this is all good.

https://github.com/securesign/secure-sign-operator/pull/46/files#diff-05cbca423c4122c2c65b3973f70f2208b5184559cb636d1e2af5f0087fca089c

https://github.com/securesign/secure-sign-operator/pull/46/files#diff-b53b22be10f54f54674230525810c35aaa06fd8fcf677d65084a29c658b2fe75

2024-01-18 13:25 UTC, bouskaJ commented
> @bouskaJ, @cooktheryan I've had to make some adjustments to how ingress is handled for rekor as with this pr there is more than one for the rekor component, let me know if this is all good.
> 
> https://github.com/securesign/secure-sign-operator/pull/46/files#diff-05cbca423c4122c2c65b3973f70f2208b5184559cb636d1e2af5f0087fca089c
> 
> https://github.com/securesign/secure-sign-operator/pull/46/files#diff-b53b22be10f54f54674230525810c35aaa06fd8fcf677d65084a29c658b2fe75

The idea behind the previous function was keeping the loosely coupled services and search by labels but it seems it was useless with our current deployment model. Your solution seems reasonable.

2024-01-18 13:32 UTC, bouskaJ requested changes

2024-01-18 13:32 UTC, bouskaJ commented on api/v1alpha1/rekor_types.go
> +	ExternalAccess ExternalAccess `json:"externalAccess,omitempty"`
`ExternalAccess` does not make sense for me. I would not deploy the UI servise at all if it is not accessible from my browser. Maybe, we can disable/enable the whole `RekorSearch` deployment.

2024-01-18 13:32 UTC, bouskaJ commented on controllers/rekor/init.go
> +		ingress := &v12.Ingress{}
Update also `fulcio` and `tuf` components to follow the same approach.

2024-01-19 12:05 UTC, JasonPowr commented on api/v1alpha1/rekor_types.go
> +	ExternalAccess ExternalAccess `json:"externalAccess,omitempty"`
ExternalAccess still needs to be passed in so an ingress can be created here, but will set it to true by default

2024-01-19 12:12 UTC, bouskaJ commented on api/v1alpha1/rekor_types.go
> +	ExternalAccess ExternalAccess `json:"externalAccess,omitempty"`
We can create the UI server **always** with ingress because it does not make sense without it. If we don't want to install the UI server, we can disable it as a whole.

2024-01-19 12:46 UTC, bouskaJ commented on api/v1alpha1/rekor_types.go
> +	ExternalAccess ExternalAccess `json:"externalAccess,omitempty"`
What about
```
 if instance.Spec.RekorSearchUI.Enabled = true {
// create deployment

 rekorSearchUiIngress, err := k8sutils.CreateIngress(ctx, i.Client, *rekorSearchUiService, ExternalAccess{}, rekorSearchUiDeploymentName, rekorSearchUiLabels) 
```
We can consider to provide `RekorSearchUI.host` field configuration.

2024-01-19 12:58 UTC, bouskaJ commented on api/v1alpha1/rekor_types.go
> +	ExternalAccess ExternalAccess `json:"externalAccess,omitempty"`
I am thinking even about 
```
//Rekor Search UI
	RekorSearchUI ExternalAccess `json:"rekorSearchUI,omitempty"`
```

It's a little hack but maybe it make sense.

2024-01-19 16:15 UTC, bouskaJ reviewed
Can you add `e2e` test? I think just simple http call is enough to verify that the UI is running.

Otherwise, LGTM. Good job. :+1:

2024-01-22 11:10 UTC, bouskaJ commented
rebase

2024-01-22 12:01 UTC, JasonPowr commented
rebased :)

2024-01-22 12:45 UTC, bouskaJ commented on api/v1alpha1/rekor_types.go
> +	RekorSearchUIPhase Phase  `json:"rekorSearchUIPhase,omitempty"`
I don't think we need another `phase` field. The Serch UI deployment status can be kept in conditions https://github.com/securesign/secure-sign-operator/issues/34 but we can leave it here and refactor later... WDYT?

2024-01-22 12:46 UTC, bouskaJ commented on e2e/byodb_test.go
> +		It("Verify Rekor Search UI is accessible", func() {
It's enough to verify it in single test workflow. I would keep this one focused on the DB.

2024-01-22 12:47 UTC, JasonPowr commented on api/v1alpha1/rekor_types.go
> +	RekorSearchUIPhase Phase  `json:"rekorSearchUIPhase,omitempty"`
Yea that sounds good to me :)

2024-01-22 12:48 UTC, bouskaJ commented on e2e/create_certs_test.go
> +					RekorSearchUI: v1alpha1.RekorSearchUI{
Maybe we can rename this test workflow as `common_install_test` or something like that and verify some kind of the default installation.

2024-01-22 12:48 UTC, bouskaJ commented on e2e/provided_certs_test.go
> +		It("Verify Rekor Search UI is accessible", func() {
Let's keep this workflow for certificate validation only.

2024-01-22 12:49 UTC, bouskaJ commented on e2e/support/tas/rekor.go
> +	Expect(list.Items).To(And(Not(BeEmpty()), HaveEach(WithTransform(func(p v1.Pod) v1.PodPhase { return p.Status.Phase }, Equal(v1.PodRunning)))))
Can you add http call to the search UI to verify that it's responding, please?

2024-01-22 12:57 UTC, JasonPowr commented on e2e/support/tas/rekor.go
> +	Expect(list.Items).To(And(Not(BeEmpty()), HaveEach(WithTransform(func(p v1.Pod) v1.PodPhase { return p.Status.Phase }, Equal(v1.PodRunning)))))
I may be misunderstanding, but I believe thats done here: https://github.com/securesign/secure-sign-operator/blob/ea8b1e7e7f5380f3dc97ba3e6c55bb27febf63df/e2e/create_certs_test.go#L181? 

Shall I move this logic to the VerifyRekorSearchUI function?

2024-01-23 07:28 UTC, bouskaJ approved these changes
Great work! Thank you.

2024-01-23 07:28 UTC, merged