[SECURESIGN-663] Add option to set an external ctlog service
securesign/secure-sign-operator pull request #465
Opened 2024-06-25 14:56 UTC by fghanmi

2024-06-26 10:05 UTC, osmman commented on api/v1alpha1/common.go
> +	//+kubebuilder:default:=6963
default port fot ctlog is `80`, port 6963 is used for metrics

2024-06-26 10:06 UTC, osmman commented on api/v1alpha1/fulcio_types.go
> +	//+kubebuilder:default:={port: 6963}
```suggestion
	//+kubebuilder:default:={port: 80}
```

2024-07-01 11:35 UTC, bouskaJ commented on internal/controller/fulcio/utils/fulcio_deployment.go
> +		ctlogUrl = fmt.Sprintf("http://ctlog.%s.svc/trusted-artifact-signer", instance.Namespace)
We can extract https://github.com/securesign/secure-sign-operator/blob/main/internal/controller/ctlog/utils/ctlog_config.go#L177 to constant and reuse for better transparency. (it is not clear from where the URL suffix is getting there).

2024-07-02 06:42 UTC, osmman requested changes

2024-07-02 06:42 UTC, osmman commented on internal/controller/fulcio/utils/fulcio_deployment.go
> +	case instance.Spec.Ctlog.Port == nil && instance.Spec.Ctlog.Address != "":
operator will fails on fatal error if `port` is `nil` and address has any non empty value. It will unable to dereference `*instance.Spec.Ctlog.Port` value if it is nil.

Please do that same way as [rekor deployment](https://github.com/securesign/secure-sign-operator/blob/main/internal/controller/rekor/utils/rekor_deployment.go#L22-L26).

2024-07-02 06:42 UTC, osmman commented on internal/controller/fulcio/utils/fulcio_deployment.go
> +		ctlogUrl = fmt.Sprintf("http://ctlog.%s.svc/trusted-artifact-signer", instance.Namespace)
Please move logic to calculate default value for address outside of util method. Here is my reasoning from [previos PR](https://github.com/securesign/secure-sign-operator/pull/196#discussion_r1629065677) for Rekor.

2024-07-02 06:43 UTC, osmman commented
Please run `make generate manifest bundle` command to generate all manifests and bundle metadata

2024-07-03 07:08 UTC, osmman commented on internal/controller/fulcio/actions/deployment.go
> +		port := int32(80)
If address is empty you should not override defined port. Here is example what should be possible to configure:
```
fulcio:
   ctlog:
      port: 9999
```
it should generate 'http://ctlog.namespace.svc:9999/trusted-artifact-signer' but your implementation will override port to `80`

2024-07-04 09:08 UTC, osmman commented
/lgtm

2024-07-04 09:09 UTC, osmman approved these changes

2024-07-04 09:13 UTC, merged