SECURESIGN-1207: fix SBJ breaking on update
securesign/secure-sign-operator pull request #502
Opened 2024-07-10 13:15 UTC by JasonPowr

2024-07-11 11:47 UTC, osmman requested changes

2024-07-11 11:47 UTC, osmman commented on internal/controller/common/utils/kubernetes/job.go
> +func GetJob(ctx context.Context, c client.Client, namespace, jobName string) (bool, *batchv1.Job, error) {
Other `Get**** functions` uses return type `(Object, error)`, so for consistency, please use the return type (*batchv1.Job, error).

2024-07-11 11:47 UTC, osmman commented on internal/controller/securesign/actions/segment_backup_job.go
> +	jobID := uuid.New().String()[:5]
It will be better to let K8s api to handle generation of uuid in name. It can be done by modify CreateJob function to use `generateName` instead of `name` on metadata. We are already doing it for Secrets and ConfigMaps

2024-07-12 13:54 UTC, osmman commented on internal/controller/common/utils/kubernetes/job.go
> +	} else if errors.IsNotFound(err) {
Please pass the `IsNotFound` error as well, and allow the caller to determine how to handle it.

2024-07-15 08:58 UTC, osmman commented on internal/controller/common/utils/kubernetes/job.go
> +	} else if errors.IsNotFound(err) {
you can remove `else if` block because there are two blocks which returns same value `nil, err`

2024-07-15 09:02 UTC, osmman commented on internal/controller/securesign/actions/segment_backup_job.go
> +	log := ctrllog.FromContext(ctx)
all our actions should have predefined logger in `i.Logger`

2024-07-15 09:14 UTC, JasonPowr commented on internal/controller/common/utils/kubernetes/job.go
> +	} else if errors.IsNotFound(err) {
Thank, I was not thinking hah

2024-07-15 09:25 UTC, osmman approved these changes

2024-07-15 10:14 UTC, merged