Add proxy e2e test
securesign/secure-sign-operator pull request #536
Opened 2024-08-01 11:52 UTC by bouskaJ

2024-08-08 13:30 UTC, osmman requested changes

2024-08-08 13:30 UTC, osmman commented on test/e2e/custom_install/proxy.go
> +				if val, present := os.LookupEnv("CI"); present && val == "true" {
this is duplicated if statement

2024-08-08 13:30 UTC, osmman commented on test/e2e/custom_install/proxy.go
> +func createProxyServer(cli runtimeCli.Client, ctx context.Context, hostname string, ns string) {
please put `ctx` as first parameter. It is common practice in go.

2024-08-08 13:30 UTC, osmman commented on test/e2e/custom_install/proxy.go
> +func installOperatorWithProxyConf(cli runtimeCli.Client, ctx context.Context, proxyHostname string, ns string) {
please put `ctx` as first parameter. It is common practice in go. please put `ctx` as first parameter. It is common practice in go.

2024-08-08 13:30 UTC, osmman commented on test/e2e/custom_install/proxy.go
> +	Expect(image).ToNot(BeNil(), "TEST_MANAGER_IMAGE can't be nil")
`Getenv` return `string` which could not be `nil`, if it is not set it will be default value `""`.  It will be better to use `LookupEnv` which return `(string, bool)`.

2024-08-08 13:30 UTC, osmman commented on test/e2e/custom_install/proxy.go
> +//go:build custom_install
currently this file do not pass `linter` check. Please fix the errors. Currently you have to run it manualy because of custom_install tag

2024-08-13 12:31 UTC, osmman requested changes

2024-08-13 12:31 UTC, osmman commented on test/e2e/custom_install/custom_install_suite_test.go
> +func TestCustomInstall(t *testing.T) {
we need to force go test to not run test parallel. it happens because of a new TestCustomInstall and it will to collision on ingress resources.

2024-08-13 13:31 UTC, bouskaJ commented on test/e2e/custom_install/custom_install_suite_test.go
> +func TestCustomInstall(t *testing.T) {
`-p 1` in the go test command disable parallel execution

2024-08-13 14:02 UTC, osmman commented on test/e2e/custom_install/custom_install_suite_test.go
> +func TestCustomInstall(t *testing.T) {
we need to add that parameter here too https://github.com/securesign/secure-sign-operator/blob/main/Makefile#L133

2024-08-19 16:35 UTC, osmman approved these changes
/lgtm

2024-08-29 13:36 UTC, bouskaJ commented
rebased

2024-08-29 13:36 UTC, merged