PoC rework ensure
securesign/secure-sign-operator pull request #740
Opened 2024-11-12 13:35 UTC by bouskaJ

2024-11-18 14:35 UTC, osmman requested changes
Hi @bouskaJ, the core functionality looks solid. However, I would like us to move this to a more reasonable package structure to avoid the common/utils clutter.

2024-11-18 14:35 UTC, osmman commented on internal/controller/common/utils/kubernetes/common.go
> +func CreateOrUpdate[T client.Object](ctx context.Context, cli client.Client, obj T, fn func(object T) error) (result controllerutil.OperationResult, err error) {
lets allow to use multiple mutate function so we can simply reuse common operations. For example to have:

```
kubernets.CreateIrUpdate(ctx, cli, &Deployment{},
   // examples for migration tasks
   migration.RemoveTUFContainer_1_1()
   migration.RemoveDeprecatedAnnotations_1_1()
   // specific mutation function
   deployment(...)
   // generic mutation fucntions
   mutate.Labels(),
   mutate.Annotations(),
   mutate.Proxy(),
   mutate.TrustedCA(),
```

2024-11-18 14:35 UTC, osmman commented on internal/controller/common/utils/ensure.go
> +func EnsureLabels(obj client.Object, labels map[string]string) {
I I correctly remember these function will need to be more complex, we need a functionality to allow remove some of annotations and labels which we manage. 

https://github.com/securesign/secure-sign-operator/blob/main/internal/controller/common/action/base_action.go#L232

2024-11-18 14:35 UTC, osmman commented on internal/controller/tuf/actions/deployment.go
> +		volume := &template.Spec.Volumes[0]
we should not use specific position in lists like `0` but we should try to find correct object based on `name`. It will be good to implement some helper method to make it easier.

2024-11-18 14:35 UTC, osmman commented on internal/controller/tuf/actions/deployment.go
> +		container := &template.Spec.Containers[0]
used hardcoded position

2024-11-25 09:31 UTC, bouskaJ commented on internal/controller/common/utils/ensure.go
> +func EnsureLabels(obj client.Object, labels map[string]string) {
you are right. I forget to implement `remove` functionality :+1:

2024-11-25 13:28 UTC, osmman requested changes
It looks good, please migrate these test scenarios for new implementation

https://github.com/securesign/secure-sign-operator/blob/main/internal/controller/common/action/base_action_test.go

2024-11-25 15:09 UTC, osmman commented
/lgtm

2024-11-25 15:09 UTC, osmman approved these changes

2024-11-26 08:41 UTC, osmman commented
/lgtm

2024-11-26 09:19 UTC, bouskaJ commented
/test tas-operator-e2e

2024-11-26 10:00 UTC, merged