[SECURESIGN-1393] Migrate to the new ensure logic
securesign/secure-sign-operator pull request #793
Opened 2024-12-18 10:06 UTC by bouskaJ

2025-01-03 09:23 UTC, bouskaJ commented
/retest

2025-01-06 11:05 UTC, osmman requested changes
We need to create unit tests for `Ensure*` functions to define how we expecting from them to modify existing objects. I think about these scenarios should be mandatory for all these functions:

- empty object -> modify to expected values
- existing object without all correct values -> no changes
- existing object contains extra values (port, rule, ...) -> **keep** or **delete** that values, based on our implementation requirements which will be important for handling upgrades
- existing object with missing values -> values will be added

2025-01-06 14:26 UTC, bouskaJ commented
> We need to create unit tests for `Ensure*` functions to define how we expecting from them to modify existing objects. I think about these scenarios should be mandatory for all these functions:
> 
> * empty object -> modify to expected values
> * existing object without all correct values -> no changes
> * existing object contains extra values (port, rule, ...) -> **keep** or **delete** that values, based on our implementation requirements which will be important for handling upgrades
> * existing object with missing values -> values will be added

@osmman tests were added but the expected behavior with existing object is a big question. I keep values that are not subject of the operator configuration unchanged with respect to default values set by another controllers but that means that we will not revert misconfiguration on those fields. What is your opinion on this?

2025-01-06 16:25 UTC, osmman commented
> > We need to create unit tests for `Ensure*` functions to define how we expecting from them to modify existing objects. I think about these scenarios should be mandatory for all these functions:
> > 
> > * empty object -> modify to expected values
> > * existing object without all correct values -> no changes
> > * existing object contains extra values (port, rule, ...) -> **keep** or **delete** that values, based on our implementation requirements which will be important for handling upgrades
> > * existing object with missing values -> values will be added
> 
> @osmman tests were added but the expected behavior with existing object is a big question. I keep values that are not subject of the operator configuration unchanged with respect to default values set by another controllers but that means that we will not revert misconfiguration on those fields. What is your opinion on this?

Exactly, that’s the problem—the choice of behavior depends heavily on the object, and I don’t expect we’ll have a uniform approach for all k8s objects:
- For example, we might override all RoleBindings.
- For labels and annotations, we only manage our own annotations and ignore others.
- For deployment, there could be cases where another operator adds a sidecar or a mounted volume.

Currently, I’m unsure how all these scenarios will be handled by our operator. I think to a straightforward approach where, for most objects, we simply override the values if it makes sense to do so. However, since the behavior can differ depending on the object type and context, it’s critical to define these cases explicitly in unit tests as documentation for our feature cahnges.

2025-01-07 10:17 UTC, osmman approved these changes

2025-01-07 13:07 UTC, merged